In [ ]:
import pandas as pd

In [2]:
data = pd.read_csv(r'D:\AQI Project\dataset\AQI_ERA5_Ground_Master_AllStations.csv')

data.head()

,Station,Date,District,Province,latitude,longitude,elevation_m,Region,In_Official_DoE_2025_Report,PM2_5_ugm3,...,ground_tmax_c,ground_tmin_c,ground_precip_src,ground_precip_src_index,ground_precip_dist_km,ground_precip_match_class,ground_temp_src,ground_temp_src_index,ground_temp_dist_km,ground_temp_match_class
0,Achham,2016-01-01,Achham (Mangalsen),Sudurpashchim,29.1427,81.2892,1485.0,Middle mountain (other),Yes,NaN,...,NaN,NaN,Mangalsen,217.0,3.87,matched,Nepalgunj Airport,420.0,121.64,none
1,Achham,2016-01-02,Achham (Mangalsen),Sudurpashchim,29.1427,81.2892,1485.0,Middle mountain (other),Yes,NaN,...,NaN,NaN,Mangalsen,217.0,3.87,matched,Nepalgunj Airport,420.0,121.64,none
2,Achham,2016-01-03,Achham (Mangalsen),Sudurpashchim,29.1427,81.2892,1485.0,Middle mountain (other),Yes,NaN,...,NaN,NaN,Mangalsen,217.0,3.87,matched,Nepalgunj Airport,420.0,121.64,none
3,Achham,2016-01-04,Achham (Mangalsen),Sudurpashchim,29.1427,81.2892,1485.0,Middle mountain (other),Yes,NaN,...,NaN,NaN,Mangalsen,217.0,3.87,matched,Nepalgunj Airport,420.0,121.64,none
4,Achham,2016-01-05,Achham (Mangalsen),Sudurpashchim,29.1427,81.2892,1485.0,Middle mountain (other),Yes,NaN,...,NaN,NaN,Mangalsen,217.0,3.87,matched,Nepalgunj Airport,420.0,121.64,none

In [8]:
na_data = data[data['latitude'].isna()]["Station"].unique()
print(na_data)

<StringArray>
['Bhimdatta / Mahendranagar',                'Biratnagar',
               'DHM Pokhara',                     'Damak',
                  'Dhankuta',                 'Dhulikhel',
               'GBS Pokhara',                  'Janakpur',
                    'Jhumka',                   'Lumbini',
                 'Nepalgunj',                'PU Pokhara',
                  'Pulchowk',                   'Sauraha',
                    'Simara',             'TU / Kirtipur']
Length: 16, dtype: str

In [13]:
data_new = data.drop(columns = ["District" , "Province" , "In_Official_DoE_2025_Report" , "ground_precip_src" , "ground_precip_match_class" , "ground_temp_src" , "ground_temp_match_class" , "has_aqi_pm25" , "has_era5"])

data_new.head()

,Station,Date,latitude,longitude,elevation_m,Region,PM2_5_ugm3,PM10_ugm3,TSP_ugm3,PM1_generic_ugm3,...,era5_surface_pressure_hpa,era5_precip_mm,era5_solar_rad_mj_m2,ground_precip_mm,ground_tmax_c,ground_tmin_c,ground_precip_src_index,ground_precip_dist_km,ground_temp_src_index,ground_temp_dist_km
0,Achham,2016-01-01,29.1427,81.2892,1485.0,Middle mountain (other),NaN,NaN,NaN,NaN,...,863.806445,0.004995,13.287984,0.0,NaN,NaN,217.0,3.87,420.0,121.64
1,Achham,2016-01-02,29.1427,81.2892,1485.0,Middle mountain (other),NaN,NaN,NaN,NaN,...,862.283815,0.026137,14.693148,0.0,NaN,NaN,217.0,3.87,420.0,121.64
2,Achham,2016-01-03,29.1427,81.2892,1485.0,Middle mountain (other),NaN,NaN,NaN,NaN,...,860.711512,0.007898,14.342076,0.0,NaN,NaN,217.0,3.87,420.0,121.64
3,Achham,2016-01-04,29.1427,81.2892,1485.0,Middle mountain (other),NaN,NaN,NaN,NaN,...,862.189095,0.004202,14.059144,0.0,NaN,NaN,217.0,3.87,420.0,121.64
4,Achham,2016-01-05,29.1427,81.2892,1485.0,Middle mountain (other),NaN,NaN,NaN,NaN,...,860.645687,1.182920,11.675744,0.0,NaN,NaN,217.0,3.87,420.0,121.64

In [17]:
missing_coordinates = {

    'Pulchowk' : (27.682581, 85.318841),
    "TU/Kirtipur" : (27.681790, 85.288250),
    "Dhulikhel" : (27.618330, 85.551940)
}

for station , (lat , long) in missing_coordinates.items():

    data_new.loc[data["Station"] == station , 'latitude'] = lat
    data_new.loc[data["Station"] == station , 'longitude'] = long


data_new = pd.DataFrame(data_new)

data_new.head()

,Station,Date,latitude,longitude,elevation_m,Region,PM2_5_ugm3,PM10_ugm3,TSP_ugm3,PM1_generic_ugm3,...,era5_surface_pressure_hpa,era5_precip_mm,era5_solar_rad_mj_m2,ground_precip_mm,ground_tmax_c,ground_tmin_c,ground_precip_src_index,ground_precip_dist_km,ground_temp_src_index,ground_temp_dist_km
0,Achham,2016-01-01,29.1427,81.2892,1485.0,Middle mountain (other),NaN,NaN,NaN,NaN,...,863.806445,0.004995,13.287984,0.0,NaN,NaN,217.0,3.87,420.0,121.64
1,Achham,2016-01-02,29.1427,81.2892,1485.0,Middle mountain (other),NaN,NaN,NaN,NaN,...,862.283815,0.026137,14.693148,0.0,NaN,NaN,217.0,3.87,420.0,121.64
2,Achham,2016-01-03,29.1427,81.2892,1485.0,Middle mountain (other),NaN,NaN,NaN,NaN,...,860.711512,0.007898,14.342076,0.0,NaN,NaN,217.0,3.87,420.0,121.64
3,Achham,2016-01-04,29.1427,81.2892,1485.0,Middle mountain (other),NaN,NaN,NaN,NaN,...,862.189095,0.004202,14.059144,0.0,NaN,NaN,217.0,3.87,420.0,121.64
4,Achham,2016-01-05,29.1427,81.2892,1485.0,Middle mountain (other),NaN,NaN,NaN,NaN,...,860.645687,1.182920,11.675744,0.0,NaN,NaN,217.0,3.87,420.0,121.64

In [20]:
print(data_new[data_new["Station"] == "Pulchowk"])

        Station        Date   latitude  longitude  elevation_m Region  \
80366  Pulchowk  2016-01-01  27.682581  85.318841          NaN    NaN
80367  Pulchowk  2016-01-02  27.682581  85.318841          NaN    NaN
80368  Pulchowk  2016-01-03  27.682581  85.318841          NaN    NaN
80369  Pulchowk  2016-01-04  27.682581  85.318841          NaN    NaN
80370  Pulchowk  2016-01-05  27.682581  85.318841          NaN    NaN
...         ...         ...        ...        ...          ...    ...
84014  Pulchowk  2025-12-27  27.682581  85.318841          NaN    NaN
84015  Pulchowk  2025-12-28  27.682581  85.318841          NaN    NaN
84016  Pulchowk  2025-12-29  27.682581  85.318841          NaN    NaN
84017  Pulchowk  2025-12-30  27.682581  85.318841          NaN    NaN
84018  Pulchowk  2025-12-31  27.682581  85.318841          NaN    NaN

       PM2_5_ugm3  PM10_ugm3  TSP_ugm3  PM1_generic_ugm3  ...  \
80366         NaN        NaN       NaN               NaN  ...
80367         NaN        NaN       NaN               NaN  ...
80368         NaN        NaN       NaN               NaN  ...
80369         NaN        NaN       NaN               NaN  ...
80370         NaN        NaN       NaN               NaN  ...
...           ...        ...       ...               ...  ...
84014         NaN        NaN       NaN               NaN  ...
84015         NaN        NaN       NaN               NaN  ...
84016         NaN        NaN       NaN               NaN  ...
84017         NaN        NaN       NaN               NaN  ...
84018         NaN        NaN       NaN               NaN  ...

       era5_surface_pressure_hpa  era5_precip_mm  era5_solar_rad_mj_m2  \
80366                        NaN             NaN                   NaN
80367                        NaN             NaN                   NaN
80368                        NaN             NaN                   NaN
80369                        NaN             NaN                   NaN
80370                        NaN             NaN                   NaN
...                          ...             ...                   ...
84014                        NaN             NaN                   NaN
84015                        NaN             NaN                   NaN
84016                        NaN             NaN                   NaN
84017                        NaN             NaN                   NaN
84018                        NaN             NaN                   NaN

       ground_precip_mm  ground_tmax_c  ground_tmin_c  \
80366               NaN            NaN            NaN
80367               NaN            NaN            NaN
80368               NaN            NaN            NaN
80369               NaN            NaN            NaN
80370               NaN            NaN            NaN
...                 ...            ...            ...
84014               NaN            NaN            NaN
84015               NaN            NaN            NaN
84016               NaN            NaN            NaN
84017               NaN            NaN            NaN
84018               NaN            NaN            NaN

       ground_precip_src_index  ground_precip_dist_km  ground_temp_src_index  \
80366                      NaN                    NaN                    NaN
80367                      NaN                    NaN                    NaN
80368                      NaN                    NaN                    NaN
80369                      NaN                    NaN                    NaN
80370                      NaN                    NaN                    NaN
...                        ...                    ...                    ...
84014                      NaN                    NaN                    NaN
84015                      NaN                    NaN                    NaN
84016                      NaN                    NaN                    NaN
84017                      NaN                    NaN                    NaN
84018                      NaN                    NaN                    NaN

       ground_temp_dist_km
80366                  NaN
80367                  NaN
80368                  NaN
80369                  NaN
80370                  NaN
...                    ...
84014                  NaN
84015                  NaN
84016                  NaN
84017                  NaN
84018                  NaN

[3653 rows x 29 columns]

In [21]:
lat_lon = data_new[["Station" , "latitude" , "longitude"]].drop_duplicates(subset = "Station")

lat_lon = lat_lon.dropna(subset = ['latitude'])

print(lat_lon.head(20))

                Station   latitude  longitude
0                Achham  29.142700  81.289200
3653         Bhaisipati  27.653100  85.302300
7306          Bhaktapur  27.673800  85.417500
10959         Bharatpur  27.672500  84.438400
29224   Dang (Deukhuri)  27.845000  82.716200
32877         Dhangadhi  28.704100  80.594500
40183         Dhulikhel  27.618330  85.551940
47489           Hetauda  27.422700  85.034400
51142              Ilam  27.047800  87.840800
62101         Khumaltar  27.646700  85.323400
69407           Mustang  28.784100  83.730000
80366          Pulchowk  27.682581  85.318841
84019              Rara  29.508300  82.093800
87672         Ratnapark  27.700000  85.310000
94978       Shankhapark  27.732800  85.342800
102284          Surkhet  28.602900  81.621000

In [ ]:
necessary_stations = ['Bhaktapur' , "Dhulikhel" , 'Pulchowk' , 'Bhaisipati' , 'Ratnapark' , 'Shankhapark' , 'TU/Kirtipur']

df = data_new[data_new['Station'].isin(necessary_stations)]

In [23]:
df.to_csv(r'D:\AQI Project\dataset\new_data.csv' , index = False)